spring:
  resources:
    chain:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl_auto: create-drop
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    sql-script-encoding: UTF-8
  redis:
    port: 6379
    host: 127.0.0.1
    password: secret

github:
  client:
    clientId: 917614cfb633b397de81
    clientSecret: c69ab2f4c6494be57d28ecb89bb4ce364ce7f29a
    accessTokenUri: https://github.com/login/oauth/access_token
    userAuthorizationUri: https://github.com/login/oauth/authorize
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://api.github.com/user


logging:
  level:
    org.springframework.security: DEBUG
