
spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: jojoldu
    password:
    sql-script-encoding: UTF-8

client:
  id: 917614cfb633b397de81
  secret: c69ab2f4c6494be57d28ecb89bb4ce364ce7f29a